var categoriesData = {
  name: 'Category',
  data: [
    {"_id":"58cc4b15fc13ae5ec7000122","categoryName":"Music and Arts","freelancers":[],
            "documents" : [{ name : "id",     required : true },
                           { name : "Degree", required : false },
                           { name : "other",  required : false }]},
    {"_id":"58cc4b15fc13ae5ec7000123","categoryName":"Accounting","freelancers":[],
            "documents" : [{ name : "id",     required : true },
                           { name : "Degree", required : true },
                           { name : "other",  required : false }]},
    {"_id":"58cc4b15fc13ae5ec7000124","categoryName":"Engineering","freelancers":[],
            "documents" : [{ name : "id",     required : true },
                           { name : "Degree", required : true },
                           { name : "other",  required : false }]},
    {"_id":"58cc4b15fc13ae5ec7000125","categoryName":"Marketing and Sales","freelancers":[],
            "documents" : [{ name : "id",     required : true },
                           { name : "Degree", required : true },
                           { name : "other",  required : false }]},
    {"_id":"58cc4b15fc13ae5ec7000126","categoryName":"Management","freelancers":[],
            "documents" : [{ name : "id",     required : true },
                           { name : "Degree", required : false },
                           { name : "other",  required : false }]},
    {"_id":"58cc4b15fc13ae5ec7000127","categoryName":"Constructions and Renovations","freelancers":[],
            "documents" : [{ name : "id",     required : true },
                           { name : "other",  required : false }]},
    {"_id":"58cc4b15fc13ae5ec7000128","categoryName":"Transport","freelancers":[],
            "documents" : [{ name : "id",              required : true },
                           { name : "Driving license", required : true },
                           { name : "other",           required : false }]},
    {"_id":"58cc4b15fc13ae5ec7000129","categoryName":"Education","freelancers":[],
            "documents" : [{ name : "id",                required : true },
                           { name : "Teaching diploma",  required: true },
                           { name : "Degree",            required : false },
                           { name : "other",             required : false }]},
    {"_id":"58cc4b15fc13ae5ec700012a","categoryName":"Medical and Sanitary","freelancers":[],
            "documents" : [{ name : "id",                                  required : true },
                           { name : "Degree",                              required : true },
                           { name : "Subscription to register of doctors", required : true },
                           { name : "other",                               required : false }]},
    {"_id":"58cc4b15fc13ae5ec700012b","categoryName":"Training and Reabilitation","freelancers":[],
            "documents" : [{ name : "id",     required : true },
                           { name : "Degree", required : false },
                           { name : "other",  required : false }]}
  ]
}
module.exports = categoriesData;